mybatis:
  mapper-locations: mapper/*/*.xml
  configuration:
    call-setters-on-nulls: true
    map-underscore-to-camel-case: true

spring:
  datasource:
    hikari:
      # driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      auto-commit: false        # AOP 로 트랜잭션을 제어하기에 false로 사용
      connection-timeout: 30000 # 커넥션 타임 아웃 (30s)
      idle-timeout: 600000      # pool 미사용 커넥션 유지 시간 (10m)
      max-lifetime: 900000      # pool 에서 미사용 커녁센 최대 수명 (15m)
      minimum-idle: 1           # 최소 커넥션 유지 개수
      maximum-pool-size: 30     # pool 에 유지시킬 수 있는 최대 커넥션 수
      pool-name: lms-hikari-pool
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        use_sql_comments: true
        format_sql: true
        show-sql: true

---

spring:
  profiles:
    active: local

---

spring:
  profiles:
    active: prod

---

spring:
  jwt:
    secret: webfirewoodjwtsigntutorialasdfasdfasdfasdfasdfjwtsigntutorialasdfasdfasdfasdfasdfwebfirewoodjwtsigntut


---