###
POST http://localhost:10100/api/auth/signup
Content-Type: application/json

{
  "accountId": "admin2",
  "password": "abc1234!",
  "roleId": "b775036a-fc78-4906-b260-95e6e2c34267",
  "keyword": "Hello!",
  "nameK": "Lee",
  "nameE": "Lee",
  "sex": "M",
  "email": "Lee@naver.com",
  "education": "001",
  "telNum": "010-4123-0214",
  "birth": "1997-01-21"
}

###
GET http://localhost:10100/unknown/bit?str=password

###
GET http://localhost:10100/member/test
Content-Type: application/json
Authorization: Bearer eyJyZWdEYXRlIjoxNjQ5NjY0MTQ3Njk5LCJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbjIgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICIsImlhdCI6MTY0OTY2NDE0NywiZXhwIjoxNjQ5Njc0OTQ3fQ.7EPFX2NjlDCdZ83tRFiGrGZGH7ePnZ2BWXxuT4a_bl7N3z4yFbW724aTFpxcX1fadwdeCikVHX1JgI82TBXdKQ


###
POST http://localhost:10100/api/auth/login
Content-Type: application/json

{
  "accountId": "admin3",
  "password": "abc1234!"
}


###
POST http://localhost:10100/api/auth/validate/id
Content-Type: application/json

{
"accountId": "admin2"
}


